# Generated by Django 4.1.9 on 2023-06-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isAgent', models.BooleanField(default=False)),
                ('skills', models.JSONField(default=list)),
                ('profile', models.CharField(default='ww.png', max_length=255)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('requirements', models.JSONField()),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.user')),
            ],
        ),
    ]
