# Generated by Django 4.1.9 on 2023-06-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hiring',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.user'),
        ),
    ]
